exports.messages = [
    "Message 1"
  , "Message 2"
  , "Message 3"
  , "Message 4"
  , "Message 5"
  , "Message 6"
  , "Message 7"
  , "Message 8"
  , "Message 9"
  , "Message 10"
  , "Message 11"
  , "Message 12"
  , "Message 13"
  , "Message 14"
  , "Message 15"
  , "Message 16"
  , "Message 17"
  , "Message 18"
  , "Message 19"
  , "Message 20"
  , "Message 21"
  , "Message 22"
  , "Message 23"
  , "Message 24"
  , "Message 25"
];

exports.fortunes = [
    "Fortune 1"
  , "Fortune 2"
  , "Fortune 3"
  , "Fortune 4"
  , "Fortune 5"
  , "Fortune 6"
  , "Fortune 7"
  , "Fortune 8"
  , "Fortune 9"
  , "Fortune 10"
  , "Fortune 11"
  , "Fortune 12"
  , "Fortune 13"
  , "Fortune 14"
  , "Fortune 15"
  , "Fortune 16"
  , "Fortune 17"
  , "Fortune 18"
  , "Fortune 19"
  , "Fortune 20"
  , "Fortune 21"
  , "Fortune 22"
  , "Fortune 23"
  , "Fortune 24"
  , "Fortune 25"
];